name: Diggity Scan
description: BOM Diggity’s primary purpose is to ensure the security and integrity of software programs.
author: Carbonetes

inputs:
  directory:
    required: true
    description: The path directory to scan.
    
runs:
  using: node16
  main: index.js
