name: Diggity Action
description: A Github Action integrated with Diggity to generate software bill-of-materials (SBOM).
author: Carbonetes

inputs:
  directory:
    required: true
    description: The path directory to scan.
  output_type:
    description: The desired SBOM output type.
  enabled_parsers:
    description: Selected parsers to scan (default all).

runs:
  using: node16
  main: index.js
